# Generated by Django 3.2.6 on 2022-12-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='C:\\Users\\Vladislav\\PycharmProjects\\coursework_6_skymarket-main\\skymarket\\django_media'),
        ),
    ]
